[package]
name = "relafix-rs"
version = "0.1.0"
authors = ["Wilke Schwiedop <wilke.schwiedop.2010w@informatik.h-brs.de>"]

[dependencies]
relax = { path = "../librelax/" }

[lib]
name = "relafix"
crate-type = ["staticlib", "cdylib"]
